<?php

namespace AcavallBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
  public function getEvetsByCategory($category)
  {
    return $this->createQueryBuilder('e')
           ->innerJoin('e.categories', 'c', 'WITH', 'c.id = :idCategory')
           ->setParameter('idCategory', $category)->getQuery()->getResult();
  }
}
