<?php

namespace AcavallBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
  public function getUsersByTicket($event)
  {
    $queryBuilder
      ->select('u.username', 'u.name', 'u.surname', 'u.email')
      ->from('Ticket', 't')
      ->innerJoin('t', 'User', 'u', 't.user = u.id')
      ->where('t.eventid'=$event);

  }
}
