<?php

namespace AcavallBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
  public function getTicketsByEvent($eventId)
  {
    $qb = $this->createQueryBuilder('t')
    ->andWhere('t.event = :event')
            ->orderBy('t.numTicket', 'ASC')
            ->setParameter('event', $eventId)
            ->getQuery();

            return $qb->getResult();
  }
}
