event_add:
    path:     /admin/createEvent
    defaults: { _controller: AcavallBundle:Event:createEvent}

event_update:
    path:     /admin/updateEvent/{eventId}
    defaults: { _controller: AcavallBundle:Event:updateEvent}

event_delete:
    path:     /admin/deleteEvent/{eventId}
    defaults: { _controller: AcavallBundle:Event:deleteEvent}
