acavall_homepage:
    path:     /
    defaults: { _controller: AcavallBundle:Default:index }

acavall_login:
    path:     /login
    defaults: { _controller: AcavallBundle:Default:login }

acavall_password:
    path:     /password
    defaults: { _controller: AcavallBundle:Default:password }

acavall_manage:
    path:     /manage
    defaults: { _controller: AcavallBundle:Default:manage }

acavall_event:
    path:     /event/{eventId}
    defaults: { _controller: AcavallBundle:Default:event }

acavall_buy:
    path:     /buy
    defaults: { _controller: AcavallBundle:Default:buy }

acavall_ticket:
    path:     /ticket
    defaults: { _controller: AcavallBundle:Default:ticket }

acavall_emailRegistry:
    path:     /emailRegistry/{name}
    defaults: { _controller: AcavallBundle:Default:emailRegistry }

acavall_emailPassword:
    path:     /emailPassword/{name}
    defaults: { _controller: AcavallBundle:Default:emailPassword }

acavall_emailTicket:
    path:     /emailTicket/{name}
    defaults: { _controller: AcavallBundle:Default:emailTicket }
