acavall_homepage:
    path:     /
    defaults: { _controller: AcavallBundle:Default:index }

acavall_register:
    path:     /register
    defaults: { _controller: AcavallBundle:Register:register }

acavall_login:
    path:     /login
    defaults: { _controller: AcavallBundle:Register:login }

acavall_password:
    path:     /password
    defaults: { _controller: AcavallBundle:Default:password }

acavall_gestor:
    path:     /gestor
    defaults: { _controller: AcavallBundle:Default:gestor }

acavall_event:
    path:     /event/{eventId}
    defaults: { _controller: AcavallBundle:Default:event }

acavall_buy:
    path:     /buy
    defaults: { _controller: AcavallBundle:Default:buy }

acavall_ticket:
    path:     /ticket
    defaults: { _controller: AcavallBundle:Default:ticket }

acavall_code:
    path:     /verifyCode/{ramCode}
    defaults: { _controller: AcavallBundle:Register:urlcode }

acavall_emailRegister:
    path:     /emailRegister/{id}/{name}
    defaults: { _controller: AcavallBundle:Default:emailRegister }
