acavall_homepage:
    path:     /
    defaults: { _controller: AcavallBundle:Default:index }

acavall_login:
    path:     /login
    defaults: { _controller: AcavallBundle:Default:login }

acavall_contrasena:
    path:     /recordarcontrasena
    defaults: { _controller: AcavallBundle:Default:recordar }
