acavall:
    resource: "@AcavallBundle/Resources/config/routing.yml"
    prefix:   /

event:
    resource: "@AcavallBundle/Resources/config/eventRouting.yml"
    prefix:   /admin

app:
    resource: '@AppBundle/Controller/'
    type: annotation
